# Generated by Django 4.2.2 on 2023-06-23 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equ', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
