# Generated by Django 4.2.2 on 2023-06-23 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equ', '0003_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='lab',
            name='admin',
        ),
        migrations.AddField(
            model_name='lab',
            name='equipments',
            field=models.ManyToManyField(related_name='labs', to='equ.equipment'),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default=0, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipment',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_set', to='equ.lab'),
        ),
        migrations.DeleteModel(
            name='EquipmentUsage',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equ.equipment'),
        ),
    ]
