# Generated by Django 4.2.2 on 2023-06-23 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equ', '0004_timeslot_remove_lab_admin_lab_equipments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='equipments',
        ),
        migrations.AddField(
            model_name='lab',
            name='lab_admin',
            field=models.OneToOneField(default=0, limit_choices_to={'groups__name': 'admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='lab_admin_of', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
