# Generated by Django 4.2.2 on 2023-06-23 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equ', '0010_alter_lab_lab_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='lab_admin',
        ),
    ]
