# Generated by Django 4.2.2 on 2023-06-23 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equ', '0012_lab_lab_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='equ.lab'),
        ),
    ]
