# Generated by Django 4.2.2 on 2023-06-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equ', '0014_alter_equipment_lab'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='usage',
            field=models.BooleanField(default=False),
        ),
    ]
