# Generated by Django 4.2.2 on 2023-06-24 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equ', '0016_equipment_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='usage',
        ),
    ]
