# Generated by Django 4.2.2 on 2023-07-05 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equ', '0020_alter_booking_end_time_alter_booking_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equ.project'),
        ),
    ]
