# Generated by Django 4.2.2 on 2023-07-05 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equ', '0021_booking_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='equ.project'),
        ),
    ]
