# Generated by Django 4.2.2 on 2023-07-09 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equ', '0022_alter_booking_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='materials',
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equ.lab')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='materials',
            field=models.ManyToManyField(to='equ.material'),
        ),
    ]
