# Generated by Django 4.2.2 on 2023-07-15 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equ', '0024_confirmed_project_confirmed_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='project',
        ),
        migrations.RemoveField(
            model_name='material',
            name='lab',
        ),
        migrations.AddField(
            model_name='material',
            name='equipment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='equ.equipment'),
        ),
    ]
