# Generated by Django 4.2.2 on 2023-08-01 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equ', '0027_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('Student', 'Student'), ('Professor', 'Professor'), ('Technician', 'Technician'), ('Other', 'Outsider')], max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('branch', models.CharField(max_length=100)),
                ('year_of_graduation', models.PositiveIntegerField(blank=True, null=True)),
                ('institute_name', models.CharField(max_length=100)),
                ('training_record', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('machines_trained_in', models.CharField(blank=True, max_length=200)),
                ('how_heard_about', models.CharField(choices=[('Peers', 'Peers'), ('Faculty', 'Faculty'), ('Technicians', 'Technicians'), ('Social Media', 'Social Media'), ('Campus Communication', 'Campus Communication'), ('Others', 'Others')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
