# Generated by Django 4.2.2 on 2023-08-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equ', '0032_alter_profile_how_heard_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='condition',
            field=models.CharField(choices=[('Very Good', 'Very Good'), ('Good', 'Good'), ('Poor', 'Poor'), ('Very Poor', 'Very Poor')], default='Good', max_length=20),
        ),
        migrations.AddField(
            model_name='material',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
