# Generated by Django 4.2.2 on 2023-08-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equ', '0033_equipment_condition_material_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='condition',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Poor', 'Poor'), ('Bad', 'Bad')], default='Good', max_length=20),
        ),
    ]
