# Generated by Django 4.2.2 on 2023-08-13 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equ', '0035_remove_useractivitylog_login_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archived_booking',
            name='materials',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='materials',
        ),
        migrations.RemoveField(
            model_name='confirmed_booking',
            name='materials',
        ),
    ]
