# Generated by Django 4.2.2 on 2023-08-13 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equ', '0036_remove_archived_booking_materials_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='equipment',
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('request_type', models.CharField(choices=[('Borrow', 'Borrow'), ('Issue', 'Issue')], max_length=10)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equ.material')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equ.lab')),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equ.category'),
        ),
    ]
