# Generated by Django 4.2.2 on 2023-08-14 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equ', '0037_remove_material_equipment_request_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='Material_Request',
        ),
    ]
