# Generated by Django 4.2.2 on 2023-08-14 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equ', '0038_rename_request_material_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='material_request',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
