# Generated by Django 4.2.2 on 2023-08-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equ', '0046_profile_organisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='organisation',
        ),
        migrations.AddField(
            model_name='lab',
            name='description',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
